import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Albert Zheng</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Albert Zheng
        </h1>


        <div className={styles.grid}>
          <Link
            href="/about"
            >
            <a
            className={styles.card}
            >

            <h2>About</h2>
            </a>
          </Link>

          <Link
            href="/work"
            >
            <a
            className={styles.card}
            >

            <h2>Work</h2>
            </a>
          </Link>

          <Link
            href="/gallery"
            >
            <a

            className={styles.card}
            >

            <h2>Gallery</h2>
            </a>
          </Link>

          <Link
            href="/contact"
            >
            <a
            className={styles.card}
            >

            <h2>Reach me</h2>
            </a>
          </Link>

        </div>
      </main>

      <footer className={styles.footer}>
        Copyright Albert Zheng 2022
      </footer>
    </div>
  )
}

export default Home
