import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Albert Zheng</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Albert Zheng
        </h1>


        <div className={styles.grid}>
          <a href="/about" className={styles.card}>
            <h2>About &rarr;</h2>
          </a>

          <a href="/work" className={styles.card}>
            <h2>Work &rarr;</h2>
          </a>

          <a
            href="/gallery"
            className={styles.card}
          >
            <h2>Gallery &rarr;</h2>
          </a>

          <a
            href="contact"
            className={styles.card}
          >
            <h2>Reach Me &rarr;</h2>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        Copyright Albert Zheng 2022
      </footer>
    </div>
  )
}

export default Home
